### ISSUE TITLE
Missing requirements and throubles

### ISSUE THREAD

**Issue by testica** [frankjdelgado/wiki-history-extractor-api#21]
- Python `2.7.10` doesn't include `pip` according to [this](https://pip.pypa.io/en/stable/installing/), so it is an extra requirement
- Missing step `sudo pip install -r requirements.txt` 
------
I got several issues installing requirements.txt : 

1. Package `PAM == 0.4.2` doesn't exist, I had to change to `PAM==0.1.2`
2. Packages `Twisted-*` (* Conch, Core, Mail, Names, Web) don't exist, I found those packages are included in Twisted.
3. Package `adium-theme-ubuntu==0.3.4` doesn't exist (is necessary ?).
4. Package `apt-xapian-index==0.46` doesn't exist (is necessary ?).
5. Package `debtags==2.0` doesn't exist (is necessary ?).
6. Package `defer==1.0.6` doesn't exist (is necessary ?).
7. Package `dirspec==13.10` doesn't exist (is necessary ?).
8. Package `duplicity==0.7.2` doesn't exist (is necessary ?).
9. Package `kombu` doesn't exist but for some reason is included in Python by default.
10. Package `mysqlclient==1.3.4` is necessary (?). We never installed mysql-server in requirements 
11. Package `oneconf==0.3.8` doesn't exist (is necessary ?).
12. Package `ply==3.7` doesn't exist, but yes `ply==3.8`.
13. Package `pycurl==7.19.5.1` for some reason require `sudo apt-get install libssl-dev libcurl4-openssl-dev python-dev`
14. Package `pygobject==3.16.2` doesn't exist, but is pre-installed in Python.
15. Package `python-apt==1.0.1` doesn't exist. I did `sudo apt-get install python-apt`
16. Package `python-debian==0.1.27` doesn't exist, but yes `python-debian==0.1.28`
17. Package `software-center-aptd-plugins==0.0.0` doesn't exist (is necessary ?).
18. Package `system-service==0.1.6` doesn't exist (is necessary ?).
19. Package `ubuntuone-client-data==14.4` doesn't exist (is necessary ?).
20. Package `unity-lens-photos==1.0` doesn't exist (is necessary ?).
21. Package `xdiagnose==3.8.1` doesn't exist (is necessary ?).
22. Building error by`cffi`. I solved with `sudo apt-get install python-cffi python-cffi libffi-dev` 
23. Building error by `pycups`. I solved with `sudo apt-get install `sudo apt-get install libcups2-dev`

Installing and Building finished!!
But.... When I ran `./run/sh server`:
#### Cryptography
I got some errors refering to `cryptography`. So I solved with `sudo pip install cryptography`.
#### Scrapy
Scapy module not found. So I think we need to add `scrapy` to requirements.txt. I solved with `sudo pip install scrapy`
#### Flask_apidoc.commands
Flask_apidoc_commands module not found. So I think we need to add `flask-apidoc` to requirements.txt. I solved with `sudo pip install flask-apidoc`

**Comment by frankjdelgado** [comment]
@testica Sorry about this. We have ran into this issue before and it seems that we screwed up the `requirement.txt` file. We will fix this as soon as we can.

**Comment by frankjdelgado** [comment]
@korenerok I have previously use a library called `pipreqs` to generate the `requirement.txt` file but that didn't solved the issue for certain python versions. Please install the library by running `pip install pipreqs` and then execute `pipreqs /path/to/project`. Let me know if that works for you.

**Comment by testica** [comment]
I tried using `pipreqs` and this is the output: 
```
pymongo==3.4.0
Flask==0.12
Flask_Script==2.0.5
requests==2.7.0
Flask_Autodoc==0.1.2
Scrapy==1.4.0
celery==4.0.2
Werkzeug==0.12.1
flask_apidoc==1.1.1
w3lib==1.18.0
coverage==4.4.1
```

**Comment by frankjdelgado** [comment]
@testica Thanks for the help. @korenerok checkout and pull from this branch `hotfix/requirements`. If that works, i will merge it into the `master` branch
