### ISSUE TITLE
Improve queries.py to accept filters by whitelist 

### ISSUE THREAD

**Issue by korenerok** [frankjdelgado/wiki-history-extractor-api#35]
Avoid the use of token/codes for parsing the filters and arguments

**Comment by frankjdelgado** [comment]
### utils.py
- Add keys to variable `whitelists` at `utils.py`. Example: For endpoint `/articles` add key `'api.revisions': ['title', 'param2', 'param3']`

### On route definition file:
- Import `filter_params` function. Example: `from . import filter_params`

- Define query params.  Example: `query = filter_params(request)` and then `db.articles(query)`
