### ISSUE TITLE
Sorting versions of articles (revisions) by timestamp

### ISSUE THREAD

**Issue by testica** [frankjdelgado/wiki-history-extractor-api#39]
In some cases, I would need the lasts/firsts N revisions, so I think that a sorting param is necessary (by timestamp especially) considering ASC and DESC options.

What do you think ?

**Comment by frankjdelgado** [comment]
@testica i just added a sorting param at `/revisions` it will only work for timestamp. You can use `/revisions?sort=asc` or `/revisions?sort=desc`

**Comment by frankjdelgado** [comment]
Also, you should check the docs, we added multiple filters. Although, i do not recommend to filter by dates, that is still on the works.

**Comment by testica** [comment]
I am trying with `http://159.203.138.13/api/v1/revisions?sort=desc` but the response order is the same that `http://159.203.138.13/api/v1/revisions?sort=asc`. It has the last api version ?

**Comment by frankjdelgado** [comment]
@testica It's a bug. The last pull request removed the sort funcionality. I already uploaded a fix
