### ISSUE TITLE
CORS support to API

### ISSUE THREAD

**Issue by testica** [frankjdelgado/wiki-history-extractor-api#49]
Modern browsers don't allow request from external domain (localhost in my case).
When I fetch to extract end-point chrome throw me 

```
Failed to load http://localhost/api/v1/extract?title=Ron%20Santa%20Teresa&locale=es: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access.
```

In my own api I am using `flask-cors`
With python flask 
```python
from flask_cors import CORS

CORS(app)
```

**Comment by frankjdelgado** [comment]
@testica try the dev branch. Shutdown the containers and run `docker-compose build`, start up the containers again (you can use `docker-compose up` if you like). Let me know if that helps so i can merge the commit to the master branch

**Comment by testica** [comment]
Works!
