### ISSUE TITLE
Add locale filter

### ISSUE THREAD

**Issue by testica** [frankjdelgado/wiki-history-extractor-api#51]
We decide that title + locale can identify an article, so is necessary the attribute locale in `/articles` and `/revisions` with the proper filter

**Comment by testica** [comment]
count, avg, and mode need title too @frankjdelgado

**Comment by frankjdelgado** [comment]
@testica I just pushed a commit to help you with that. I test it with RabbitMQ using ES and EN, let me know if you find any errors
